---
driver:
  name: vagrant

platforms:
  - name: ubuntu-16.04
  # - name: ubuntu-12.04
  # - name: debian-8.2
  # - name: centos-7.2
  # - name: centos-6.7
  # - name: centos-5.11

suites:
  - name: default
    run_list:
      - recipe[clamav]
  - name: enabled
    run_list:
      - recipe[clamav]
    attributes:
      clamav:
        clamd:
          enabled: true
        freshclam:
          enabled: true
  - name: remove
    run_list:
      - recipe[clamav_test::remove]
